[2023-12-20T21:06:22.774+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:22.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:06:22.777+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:06:22.777+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:22.792+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:06:22.789+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:06:22.807+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:22.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.108 seconds
[2023-12-20T21:06:53.119+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:53.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:06:53.126+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:06:53.126+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:53.142+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:06:53.139+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:06:53.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:06:53.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.378 seconds
[2023-12-20T21:07:24.391+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:07:24.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:07:24.394+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:07:24.394+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:07:24.408+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:07:24.405+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:07:24.409+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:07:24.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.036 seconds
[2023-12-20T21:08:33.197+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:08:33.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:08:33.202+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:08:33.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:08:33.217+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:08:33.213+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:08:33.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:08:33.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.044 seconds
[2023-12-20T21:09:03.333+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:03.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:09:03.337+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:09:03.337+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:03.354+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:09:03.349+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:09:03.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:03.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.044 seconds
[2023-12-20T21:09:33.697+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:33.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:09:33.699+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:09:33.699+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:33.712+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:09:33.709+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:09:33.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:09:33.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.036 seconds
[2023-12-20T21:10:04.168+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:04.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:10:04.171+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:10:04.171+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:04.185+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:10:04.182+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:10:04.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:04.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.038 seconds
[2023-12-20T21:10:34.276+0000] {processor.py:157} INFO - Started process (PID=262) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:34.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:10:34.279+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:10:34.278+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:34.294+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:10:34.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:10:34.296+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:10:34.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.041 seconds
[2023-12-20T21:11:04.351+0000] {processor.py:157} INFO - Started process (PID=318) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:04.352+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:11:04.354+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:11:04.354+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:04.366+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:11:04.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:11:04.367+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:04.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:11:34.618+0000] {processor.py:157} INFO - Started process (PID=374) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:34.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:11:34.621+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:11:34.621+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:34.635+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:11:34.631+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:11:34.636+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:11:34.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.039 seconds
[2023-12-20T21:12:05.236+0000] {processor.py:157} INFO - Started process (PID=430) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:05.237+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:12:05.239+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:12:05.239+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:05.256+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:12:05.252+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:12:05.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:05.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.048 seconds
[2023-12-20T21:12:35.376+0000] {processor.py:157} INFO - Started process (PID=486) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:35.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:12:35.379+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:12:35.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:35.392+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:12:35.389+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:12:35.393+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:12:35.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.046 seconds
[2023-12-20T21:13:05.699+0000] {processor.py:157} INFO - Started process (PID=542) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:05.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:13:05.701+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:13:05.701+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:05.715+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:13:05.712+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:13:05.717+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:05.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:13:35.768+0000] {processor.py:157} INFO - Started process (PID=598) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:35.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:13:35.770+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:13:35.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:35.783+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:13:35.780+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:13:35.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:13:35.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:14:05.867+0000] {processor.py:157} INFO - Started process (PID=654) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:05.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:14:05.870+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:14:05.870+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:05.881+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:14:05.879+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:14:05.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:05.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:14:36.120+0000] {processor.py:157} INFO - Started process (PID=710) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:36.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:14:36.122+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:14:36.122+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:36.134+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:14:36.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:14:36.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:14:36.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:15:06.616+0000] {processor.py:157} INFO - Started process (PID=766) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:06.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:15:06.618+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:15:06.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:06.631+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:15:06.627+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:15:06.632+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:06.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:15:37.254+0000] {processor.py:157} INFO - Started process (PID=822) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:37.255+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:15:37.257+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:15:37.257+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:37.270+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:15:37.266+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:15:37.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:15:37.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:16:07.706+0000] {processor.py:157} INFO - Started process (PID=878) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:07.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:16:07.709+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:16:07.709+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:07.724+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:16:07.720+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:16:07.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:07.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.038 seconds
[2023-12-20T21:16:38.279+0000] {processor.py:157} INFO - Started process (PID=934) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:38.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:16:38.282+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:16:38.281+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:38.296+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:16:38.292+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:16:38.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:16:38.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.041 seconds
[2023-12-20T21:17:08.560+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:08.561+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:17:08.562+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:17:08.562+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:08.578+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:17:08.575+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:17:08.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:08.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.043 seconds
[2023-12-20T21:17:38.901+0000] {processor.py:157} INFO - Started process (PID=1046) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:38.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:17:38.903+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:17:38.903+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:38.917+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:17:38.913+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:17:38.918+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:17:38.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.039 seconds
[2023-12-20T21:18:09.122+0000] {processor.py:157} INFO - Started process (PID=1102) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:09.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:18:09.125+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:18:09.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:09.139+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:18:09.136+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:18:09.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:09.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.039 seconds
[2023-12-20T21:18:39.355+0000] {processor.py:157} INFO - Started process (PID=1158) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:39.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:18:39.357+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:18:39.357+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:39.371+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:18:39.368+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:18:39.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:18:39.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:19:09.736+0000] {processor.py:157} INFO - Started process (PID=1214) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:09.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:19:09.739+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:19:09.738+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:09.753+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:19:09.749+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:19:09.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:09.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:19:40.160+0000] {processor.py:157} INFO - Started process (PID=1270) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:40.161+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:19:40.163+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:19:40.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:40.176+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:19:40.173+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:19:40.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:19:40.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.038 seconds
[2023-12-20T21:20:10.284+0000] {processor.py:157} INFO - Started process (PID=1326) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:10.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:20:10.287+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:20:10.287+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:10.300+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:20:10.297+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:20:10.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:10.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.036 seconds
[2023-12-20T21:20:40.474+0000] {processor.py:157} INFO - Started process (PID=1382) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:40.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:20:40.476+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:20:40.476+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:40.490+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:20:40.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:20:40.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:20:40.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:21:10.822+0000] {processor.py:157} INFO - Started process (PID=1438) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:10.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:21:10.825+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:21:10.824+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:10.837+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:21:10.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:21:10.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:10.855+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:21:40.887+0000] {processor.py:157} INFO - Started process (PID=1494) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:40.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:21:40.890+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:21:40.890+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:40.903+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:21:40.901+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:21:40.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:21:40.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:22:11.275+0000] {processor.py:157} INFO - Started process (PID=1550) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:11.275+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:22:11.278+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:22:11.277+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:11.291+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:22:11.288+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:22:11.292+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:11.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.038 seconds
[2023-12-20T21:22:41.634+0000] {processor.py:157} INFO - Started process (PID=1606) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:41.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:22:41.637+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:22:41.637+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:41.651+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:22:41.648+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:22:41.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:22:41.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.037 seconds
[2023-12-20T21:23:11.952+0000] {processor.py:157} INFO - Started process (PID=1662) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:11.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:23:11.955+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:23:11.954+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:11.966+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:23:11.964+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:23:11.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:11.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.033 seconds
[2023-12-20T21:23:42.300+0000] {processor.py:157} INFO - Started process (PID=1718) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:42.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:23:42.303+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:23:42.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:42.315+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:23:42.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:23:42.316+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:23:42.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.033 seconds
[2023-12-20T21:24:12.668+0000] {processor.py:157} INFO - Started process (PID=1774) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:12.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:24:12.672+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:24:12.671+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:12.685+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:24:12.682+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:24:12.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:12.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.035 seconds
[2023-12-20T21:24:43.076+0000] {processor.py:157} INFO - Started process (PID=1830) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:43.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:24:43.079+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:24:43.079+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:43.091+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:24:43.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:24:43.092+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:24:43.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.036 seconds
[2023-12-20T21:25:13.445+0000] {processor.py:157} INFO - Started process (PID=1886) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:13.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:25:13.448+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:25:13.447+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:13.461+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:25:13.458+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:25:13.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:13.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.036 seconds
[2023-12-20T21:25:43.759+0000] {processor.py:157} INFO - Started process (PID=1942) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:43.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:25:43.762+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:25:43.762+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:43.775+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:25:43.772+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:25:43.776+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:25:43.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.034 seconds
[2023-12-20T21:26:14.167+0000] {processor.py:157} INFO - Started process (PID=1998) to work on /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:26:14.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pizza_order_dag.py for tasks to queue
[2023-12-20T21:26:14.170+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:26:14.170+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:26:14.191+0000] {logging_mixin.py:154} INFO - [2023-12-20T21:26:14.185+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pizza_order_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pizza_order_dag.py", line 8, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
[2023-12-20T21:26:14.193+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pizza_order_dag.py
[2023-12-20T21:26:14.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pizza_order_dag.py took 0.054 seconds
