[2023-12-21T21:00:43.583+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pizza_order_dag.check_order_task manual__2023-12-21T21:00:43.042866+00:00 [queued]>
[2023-12-21T21:00:43.598+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pizza_order_dag.check_order_task manual__2023-12-21T21:00:43.042866+00:00 [queued]>
[2023-12-21T21:00:43.599+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-21T21:00:43.618+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): check_order_task> on 2023-12-21 21:00:43.042866+00:00
[2023-12-21T21:00:43.624+0000] {standard_task_runner.py:57} INFO - Started process 279 to run task
[2023-12-21T21:00:43.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pizza_order_dag', 'check_order_task', 'manual__2023-12-21T21:00:43.042866+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/pizza_order_dag.py', '--cfg-path', '/tmp/tmp5xhejcqy']
[2023-12-21T21:00:43.627+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask check_order_task
[2023-12-21T21:00:43.665+0000] {task_command.py:416} INFO - Running <TaskInstance: pizza_order_dag.check_order_task manual__2023-12-21T21:00:43.042866+00:00 [running]> on host 20e184a2eb37
[2023-12-21T21:00:43.757+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pizza_order_dag' AIRFLOW_CTX_TASK_ID='check_order_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T21:00:43.042866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T21:00:43.042866+00:00'
[2023-12-21T21:00:43.956+0000] {logging_mixin.py:154} INFO - [X] - all right
[2023-12-21T21:00:43.957+0000] {python.py:194} INFO - Done. Returned value was: Order object (1)
[2023-12-21T21:00:43.963+0000] {xcom.py:661} ERROR - Object of type Order is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-21T21:00:43.965+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pizza.models.Order'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Order is not JSON serializable
[2023-12-21T21:00:43.973+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pizza_order_dag, task_id=check_order_task, execution_date=20231221T210043, start_date=20231221T210043, end_date=20231221T210043
[2023-12-21T21:00:43.986+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task check_order_task (Object of type Order is not JSON serializable; 279)
[2023-12-21T21:00:44.000+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T21:00:44.020+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
